### ISSUE TITLE
NullPointerException in vanKreveldNew

### ISSUE THREAD

**Issue by moritzbeck** [chrih/Projekt_Algo_GIS#7]
Bei mir ergibt der Testlauf folgendes Ergebnis:

```
Calculating Viewsheds for the Point (5,5)
sweep 116.955.673.596 ns
brute  40.949.062.048 ns
prute  30.521.187.125 ns
Exception in thread "main" java.lang.NullPointerException
    at de.uniwue.algogis.viewshed.sweep.vanKreveldNew.updateEventlist(vanKreveldNew.java:183)
    at de.uniwue.algogis.viewshed.sweep.vanKreveldNew.calculateViewshed(vanKreveldNew.java:89)
    at de.uniwue.algogis.viewshed.ViewshedAnalysis.calculateViewshed(ViewshedAnalysis.java:11)
    at de.uniwue.algogis.viewshed.Test.lambda$4(Test.java:43)
    at de.uniwue.algogis.viewshed.Test$$Lambda$5/764977973.get(Unknown Source)
    at de.uniwue.algogis.viewshed.Test.benchmark(Test.java:69)
    at de.uniwue.algogis.viewshed.Test.lambda$0(Test.java:43)
    at de.uniwue.algogis.viewshed.Test$$Lambda$3/999966131.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576)
    at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255)
    at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
    at de.uniwue.algogis.viewshed.Test.main(Test.java:44)
```

**Comment by chrih** [comment]
Hab gerade die aktuellste Version von vanKreveldNew hochgeladen. Bei mir läuft der Test durch.

**Comment by moritzbeck** [comment]
Ich erhalte keine Exception mehr.
